/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

const path = process.env.NODE_ENV === 'development'? '/notebook.glb' : '/portfolio/notebook.glb'

const Model = (props) => {
  const {nodes, materials} = useGLTF(path)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lowpoly_Notebook_Cube001.geometry} material={nodes.Lowpoly_Notebook_Cube001.material} />
    </group>
  )
}

useGLTF.preload(path)
export default Model
