const GRAVITY_RADIUS = 120
const LAND_RADIUS = 10
const PARK_DISTANCE = 14
const GRAVITY_STRENGTH = 18
const AUTO_BRAKE = 0.92
const THRUST = 0.015 // 👈 slow acceleration
const DAMPING = 0.98

export {GRAVITY_RADIUS, LAND_RADIUS, PARK_DISTANCE, GRAVITY_STRENGTH, AUTO_BRAKE, THRUST, DAMPING}
